apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastapi-sandbox-postgres
spec:
  serviceName: "postgres"
  selector:
    matchLabels:
      app: fastapi-sandbox-postgres
  template:
    metadata:
      labels:
        app: fastapi-sandbox-postgres
    spec:
      containers:
      - name: db
        image: postgres:15.3-alpine
        envFrom:
        - secretRef:
            name: fastapi-sandbox-postgres-secrets
        - configMapRef:
            name: fastapi-sandbox-postgres-config-map
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: fastapi-sandbox-postgres-pvc