services:
  api:
    container_name: fastapi-sandbox
    depends_on:
      postgres:
        condition: service_started
      db-migrations:
        condition: service_completed_successfully
    build:
      context: ./
    volumes:
      - ./src:/fastapi-sandbox/src
    ports:
      - 8000:8000
    restart: on-failure:5
    env_file:
      - .env

  db-migrations:
    container_name: fastapi-sandbox-db-migrations
    depends_on:
      postgres:
        condition: service_started
    build:
      context: ./
    command: /fastapi-sandbox/scripts/run_migrations.sh
    restart: "no"
    env_file:
      - .env
    environment:
      DB_MIGRATION_RETRIES: 5
      DB_MIGRATION_SLEEP: 2

  postgres:
    container_name: postgres
    image: 'postgres:18.2-alpine'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-v18:/var/lib/postgresql

volumes:
  db-v18:
    driver: local
