apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-sandbox-migration-job
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrations
        image: jstenghele/juans-fastapi-sandbox:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "/fastapi-sandbox/scripts/run_migrations.sh"]
        workingDir: /fastapi-sandbox
        envFrom:
        - secretRef:
            name: fastapi-sandbox-secrets
        - configMapRef:
            name: fastapi-sandbox-config-map
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
